POST http://127.0.0.1:8000/signup
Content-Type: application/json

{
  "username": "idorabin1235",
  "password": "Pass1234!",
  "email": "adam@mail.com",
  "first_name": "Ido",
  "last_name": "Rabin"
}


###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "idorabin", "password": "idoidoido1" }

###

GET http://127.0.0.1:8000/user_homeworks
Content-Type: application/json
Authorization: token d5a6fdb25f99d894533215faffe6f0fb1075fb8d