# Generated by Django 4.2.20 on 2025-05-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeWork", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="file_id",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
