# Generated by Django 4.2.20 on 2025-05-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeWork", "0002_homework_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fillinblank",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fill_in_blanks",
                to="homeWork.homework",
            ),
        ),
        migrations.AlterField(
            model_name="grammaticalphenomenon",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grammatical_phenomena",
                to="homeWork.homework",
            ),
        ),
        migrations.AlterField(
            model_name="vocabularymatch",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vocab_matches",
                to="homeWork.homework",
            ),
        ),
    ]
