# Generated by Django 4.2.20 on 2025-05-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeWork", "0005_alter_grammaticalphenomenon_homework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grammaticalphenomenon",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grammatical_phenomenon",
                to="homeWork.homework",
            ),
        ),
    ]
